version: '1'
services:
  app:
    image: prueba-tecnica
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
        - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
